# Generated by Django 4.0.4 on 2023-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GISource',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_cn', models.CharField(blank=True, max_length=100, null=True)),
                ('university_en', models.CharField(blank=True, max_length=100, null=True)),
                ('country_cn', models.CharField(blank=True, max_length=100, null=True)),
                ('country_en', models.CharField(blank=True, max_length=100, null=True)),
                ('job_cn', models.CharField(blank=True, max_length=100, null=True)),
                ('job_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('title_cn', models.CharField(blank=True, max_length=400, null=True)),
                ('title_en', models.CharField(blank=True, max_length=400, null=True)),
                ('label_physical_geo', models.SmallIntegerField(blank=True, null=True)),
                ('label_human_geo', models.SmallIntegerField(blank=True, null=True)),
                ('label_urban', models.SmallIntegerField(blank=True, null=True)),
                ('label_gis', models.SmallIntegerField(blank=True, null=True)),
                ('label_rs', models.SmallIntegerField(blank=True, null=True)),
                ('label_gnss', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_public', models.SmallIntegerField()),
                ('is_deleted', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'GISource',
                'managed': False,
            },
        ),
    ]
