# Generated by Django 4.0.4 on 2023-01-16 12:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a833b89e-959b-11ed-b762-3c9c0fb506b1'), editable=False, primary_key=True, serialize=False, verbose_name='用户UUID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='电话号码'),
        ),
    ]
