# Generated by Django 4.0.4 on 2023-02-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
